export const LOADING_PHRASES = [
  "thinkimg...",
  "bloggin in",
  "computeringg",
  "writyng",
  "procesiing thoughnt",
  "cramfting wrdos",
  "brain workign",
  "typyng away",
  "composering",
  "wordsmithing",
  "creafting blogg",
  "assemblyng thoughnt",
  "writyng magesty",
  "bloggin royaly",
  "computler thinkimg",
  "crafyng sentance",
  "processyng wrdos",
  "royaly typyng",
  "bloggin awya",
  "assemblyng wrdos togethre",
  "cramfting idea",
  "royaly processyng blogg contrent",
  "thinkimg very hardley",
  "writyng upp storys",
  "computler wokring magicaly",
  "bloggin",
  "creafting delightfull sentances",
  "processyng",
  "typyng away furiosly",
  "computering the thoughnts",
  "writyng royaly magnificennt bloggs",
  "bloggin magesty",
  "assemblyng wrdos into sentances",
  "creafting",
  "royaly thinkimg aboutt thingss",
  "computler processyng wrdos",
  "writyng upp delightfull contrent",
  "bloggin awayj",
  "finishyng upp the writyng",
];
