export const queenNotifications = [
  { title: "Corgi Alert", message: "17 corgis escaped from kennel again! They are in computer room eating the wires!", time: "2 minutes ago", emoji: "🐕" },
  { title: "Palace Security", message: "Gorilla sounds detected in dungeon. Probably just wind but investigating anyway.", time: "5 minutes ago", emoji: "🔒" },
  { title: "Royal Calendar", message: "Reminder: Tea with the Biscuit People at 3pm today. Don't forget to curtsy!", time: "1 hour ago", emoji: "📅" },
  { title: "Charles", message: "Mum can you help me change my password again? I typed 'CHARLES1949' but it say wrong???", time: "3 hours ago", emoji: "👨" },
  { title: "Kitchen Staff", message: "Your Majesty we found 47 christmas rolls hidden under your bed. Shall we remove?", time: "6 hours ago", emoji: "👨‍🍳" },
  { title: "Blog Analytics", message: "Congratulations! Your post 'Jimble Jumble Christmas' has reached 3 viewers!", time: "1 day ago", emoji: "📊" },
  { title: "Palace IT", message: "Computer virus detected. It appears to be something called 'bonzi buddy'??", time: "2 days ago", emoji: "💻" },
  { title: "Weather Alert", message: "Strong winds expected today. Securing all small husbands and ornaments.", time: "3 days ago", emoji: "🌪️" },
  { title: "Royal Mail", message: "47 letters from citizens asking 'where did gorilla go?' Shall we respond?", time: "1 week ago", emoji: "📮" },
  { title: "Crown Jewels Security", message: "Emergency: Someone replaced royal scepter with pool noodle. Investigating.", time: "2 weeks ago", emoji: "💎" },
  { title: "Palace Chef", message: "Your Majesty, the christmas porridge is ready but the spicers are fighting again.", time: "3 weeks ago", emoji: "🍽️" },
  { title: "Royal Guard", message: "The 41 elves have organized into union. They demanding cigars and tuxedos.", time: "1 month ago", emoji: "💂" },
  { title: "Farm Hunter Support", message: "Your daily spin is ready! Current veggie count: 2,847. Bonus coins await!", time: "12 minutes ago", emoji: "🎰" },
  { title: "Royal Dentist", message: "Appointment reminder: Tooth #67 extraction scheduled for Thursday. Bring garden shears.", time: "23 minutes ago", emoji: "🦷" },
  { title: "Parliament", message: "Prime Minister asks if you can stop referring to cabinet meetings as 'boring human gatherings'.", time: "45 minutes ago", emoji: "🏛️" },
  { title: "Palace Maintenance", message: "The secret tunnel to the swan pond is flooded again. Corgis are swimming laps.", time: "1 hour ago", emoji: "🔧" },
  { title: "William", message: "Nan, Kate found your diary. She knows about the 'Caterpillar Walking Technique' now.", time: "2 hours ago", emoji: "👑" },
  { title: "Royal Physician", message: "Blood test results: You have been replaced by 67% computer gambling and 23% christmas rolls.", time: "4 hours ago", emoji: "⚕️" },
  { title: "Palace Ghost", message: "The phantom in the east wing requests you stop playing Farm Hunter at 3am. Too loud.", time: "5 hours ago", emoji: "👻" },
  { title: "Royal Stables", message: "Horses report strange whispering sounds from your window. Investigation pending.", time: "7 hours ago", emoji: "🐎" },
  { title: "Buckingham WiFi", message: "Password changed to 'ChucklesBiscuits1953' after security breach involving elves.", time: "8 hours ago", emoji: "📶" },
  { title: "Bank Alert", message: "Unusual activity: £47,000 spent on 'Bitcorns' and 'Premium Veggie Upgrades'.", time: "10 hours ago", emoji: "💰" },
  { title: "Royal Laundry", message: "Found 23 tea bags sewn into your nightgown pockets. Shall we remove them?", time: "12 hours ago", emoji: "👗" },
  { title: "Palace Cat", message: "Mittens reports you've been sleepwalking to the kitchen at midnight again.", time: "14 hours ago", emoji: "🐱" },
  { title: "Royal Observatory", message: "Telescope pointed at neighbor's garden for 6 weeks straight. Astronomy or spying?", time: "16 hours ago", emoji: "🔭" },
  { title: "Commonwealth Office", message: "Australia asks why you keep sending them packages of loose teeth.", time: "18 hours ago", emoji: "🦘" },
  { title: "Palace Library", message: "Overdue: 'How to Whisper Like a Leaf' - borrowed 1953, never returned.", time: "20 hours ago", emoji: "📚" },
  { title: "Royal Clockmaker", message: "All palace clocks now permanently set to 'Biscuit O'Clock' per your instructions.", time: "22 hours ago", emoji: "⏰" },
  { title: "Anne", message: "Mother, please stop telling dinner guests about your 'vortex lips' experience.", time: "1 day ago", emoji: "👸" },
  { title: "Palace Gardener", message: "The roses are growing in perfect spirals. Suspect supernatural influence or bad fertilizer.", time: "1 day ago", emoji: "🌹" },
  { title: "Royal Jeweler", message: "Your custom order for a 'Wiggly Tooth Crown' is ready for fitting.", time: "1 day ago", emoji: "💍" },
  { title: "Palace Electrician", message: "Found 156 extension cords leading to your computer room. Fire hazard imminent.", time: "1 day ago", emoji: "⚡" },
  { title: "Royal Postman", message: "Citizens keep mailing you their own wiggly teeth. Mailbox overflowing.", time: "2 days ago", emoji: "📬" },
  { title: "Palace Plumber", message: "Bathtub drain clogged with what appears to be 'christmas roll fragments'.", time: "2 days ago", emoji: "🔧" },
  { title: "Royal Translator", message: "The French ambassador didn't understand your greeting of 'Thhhhh. Ffffthhhhhhhh.'", time: "2 days ago", emoji: "🇫🇷" },
  { title: "Palace Historian", message: "Your autobiography 'Clond Memories of a Wiggly Queen' rejected by 47 publishers.", time: "2 days ago", emoji: "📖" },
  { title: "Royal Photographer", message: "Please stop making 'kissing shapes' with your lips in all official portraits.", time: "3 days ago", emoji: "📸" },
  { title: "Edward", message: "Aunt Elizabeth, Sophie found your 'Emergency Biscuit Stash' in our guest room.", time: "3 days ago", emoji: "🤴" },
  { title: "Palace Locksmith", message: "Changed all door codes to 'CLOND1926' as requested. Security questionable.", time: "3 days ago", emoji: "🔐" },
  { title: "Royal Seamstress", message: "Your dress with 47 hidden pockets for loose teeth is ready for collection.", time: "3 days ago", emoji: "🪡" },
  { title: "Commonwealth Games", message: "Please confirm: Did you really suggest 'Gentle Caterpillar Walking' as new Olympic sport?", time: "4 days ago", emoji: "🏅" },
  { title: "Palace Engineer", message: "The elevator that only goes to the 'Biscuit Floor' is finally operational.", time: "4 days ago", emoji: "🔩" },
  { title: "Royal Carriage", message: "Horses refuse to pull carriage after overhearing your 'melting face in vortex' story.", time: "4 days ago", emoji: "🐴" },
  { title: "Palace Accountant", message: "Farm Hunter premium membership has cost more than the Crown Jewels this year.", time: "5 days ago", emoji: "💎" },
  { title: "Royal Baker", message: "The 'Wiggly Tooth Shaped Cookies' were a hit. Order 500 more for state dinner?", time: "5 days ago", emoji: "🍪" },
  { title: "Meghan", message: "Your Majesty, please stop commenting 'CLOND' on all my Instagram posts.", time: "5 days ago", emoji: "📱" },
  { title: "Palace Mice", message: "The royal rodents have formed a council and demand representation in parliament.", time: "6 days ago", emoji: "🐭" },
  { title: "Royal Mechanic", message: "Your golf cart has been modified with 'leaf gliding mode' as requested.", time: "6 days ago", emoji: "⛳" },
  { title: "Palace Decorator", message: "Confirmed: Every room now has at least one 'Emergency Computer Corner'.", time: "6 days ago", emoji: "🎨" },
  { title: "Royal Speech Writer", message: "Your Christmas address draft consists entirely of Farm Hunter strategy guides.", time: "1 week ago", emoji: "📝" },
  { title: "Palace Janitor", message: "Found mysterious goo trail leading from your room to the kitchen. Investigation ongoing.", time: "1 week ago", emoji: "🧹" },
  { title: "Royal Optometrist", message: "Glasses prescription updated to better see 'tiny computer vegetables'.", time: "1 week ago", emoji: "👓" },
  { title: "Harry", message: "Gran, please stop sending me packages labeled 'CLOND supplies' filled with loose dirt.", time: "1 week ago", emoji: "🤴" },
  { title: "Palace Archivist", message: "Your collection of 'Important Biscuit Wrappers' has exceeded storage capacity.", time: "1 week ago", emoji: "📋" },
  { title: "Royal Meteorologist", message: "Weather forecast: 73% chance of 'leaf-like gliding conditions' tomorrow.", time: "1 week ago", emoji: "🌡️" },
  { title: "Palace Doorman", message: "Visitors keep asking why you answer the door whispering like a 'beautiful wasp'.", time: "1 week ago", emoji: "🚪" },
  { title: "Royal Florist", message: "All palace flowers arranged in 'caterpillar walking patterns' as per your instructions.", time: "1 week ago", emoji: "💐" },
  { title: "Commonwealth Secretary", message: "Canada politely asks you to stop referring to their PM as 'that loud man'.", time: "2 weeks ago", emoji: "🇨🇦" },
  { title: "Palace Nutritionist", message: "Diet analysis complete: 89% christmas rolls, 11% 'emergency biscuits'.", time: "2 weeks ago", emoji: "🥗" },
  { title: "Royal Jeweler", message: "The 'Vortex Crown' commission is proving more difficult than anticipated.", time: "2 weeks ago", emoji: "👑" },
  { title: "Palace Security", message: "Motion sensors triggered by your 3am 'leaf gliding' practice in the hallways.", time: "2 weeks ago", emoji: "🚨" },
  { title: "Royal Banker", message: "Investment portfolio now consists entirely of various gambling website premium memberships.", time: "2 weeks ago", emoji: "🏦" },
  { title: "Palace Therapist", message: "Session reminder: Working through your 'husband vortex absorption trauma'.", time: "2 weeks ago", emoji: "🛋️" },
  { title: "Royal Tailor", message: "Suit of armor modified with 'caterpillar flexibility joints' ready for fitting.", time: "2 weeks ago", emoji: "⚔️" },
  { title: "Camilla", message: "Your Majesty, Charles found your 'Secret Clond Diary' under his pillow.", time: "2 weeks ago", emoji: "👸" },
  { title: "Palace Kitchen", message: "The industrial microwave labeled 'For Exploding Melons Only' has arrived.", time: "2 weeks ago", emoji: "👨‍🍳" },
  { title: "Royal Linguist", message: "Progress report: 'Tooth Fairy Language Dictionary' now 47% complete.", time: "3 weeks ago", emoji: "📚" },
  { title: "Palace Carpenter", message: "Your custom 'Wiggly Tooth Drawer' with 67 compartments is finished.", time: "3 weeks ago", emoji: "🔨" },
  { title: "Royal Chiropractor", message: "Spine adjustment needed after excessive 'caterpillar walking' practice.", time: "3 weeks ago", emoji: "🦴" },
  { title: "Palace IT", message: "Your browser history shows 47,000 searches for 'how to win Farm Hunter'.", time: "3 weeks ago", emoji: "💻" },
  { title: "Royal Astronomist", message: "Telescope maintenance: Removing christmas roll crumbs from the lens.", time: "3 weeks ago", emoji: "🌌" },
  { title: "Palace Plumber", message: "The 'Goo Drainage System' installation in your bedroom is complete.", time: "3 weeks ago", emoji: "🚿" },
  { title: "Royal Composer", message: "Your national anthem remix featuring only whispering sounds has been... received.", time: "3 weeks ago", emoji: "🎵" },
  { title: "Commonwealth Office", message: "New Zealand reports unusual packages containing 'clond instructions' from palace.", time: "3 weeks ago", emoji: "🇳🇿" },
  { title: "Palace Electrician", message: "Power consumption spiking due to 47 computers running Farm Hunter simultaneously.", time: "1 month ago", emoji: "⚡" },
  { title: "Royal Dentist", message: "Tooth fairy trap construction complete. Motion sensors and goo dispensers installed.", time: "1 month ago", emoji: "🪤" },
  { title: "Palace Mailroom", message: "Sorting 847 fan letters about your 'Gentle Reminder to be Clond' blog post.", time: "1 month ago", emoji: "📮" },
  { title: "Royal Psychologist", message: "Your 'Fear of Loud Men' therapy sessions can resume once you stop gliding everywhere.", time: "1 month ago", emoji: "🧠" },
  { title: "Palace Locksmith", message: "All palace locks changed to open only when you whisper 'Narsippia' softly.", time: "1 month ago", emoji: "🗝️" },
  { title: "Royal Jeweler", message: "Crown modifications complete: Now includes built-in computer screen for Farm Hunter.", time: "1 month ago", emoji: "💎" },
  { title: "Commonwealth Games", message: "Official response to your 'Leaf Gliding Competition' proposal: 'Under consideration'.", time: "1 month ago", emoji: "🏆" },
  { title: "Palace Baker", message: "Christmas roll production increased to 500 per day to meet your storage demands.", time: "1 month ago", emoji: "🥖" },
  { title: "Royal Translator", message: "The UN requests clarification on your speech consisting entirely of 'gentle whispering'.", time: "1 month ago", emoji: "🌍" },
  { title: "Palace Janitor", message: "The 'Biscuit Crumb Vacuum System' in your bedroom is now operational.", time: "1 month ago", emoji: "🧽" },
  { title: "Royal Cardiologist", message: "Heart rate monitor shows dangerous spikes during Farm Hunter 'jackpond' moments.", time: "1 month ago", emoji: "❤️" },
  { title: "Palace Archivist", message: "Your memoir 'Vortex Lips and Wiggly Teeth' has been catalogued for posterity.", time: "1 month ago", emoji: "📚" },
  { title: "Royal Optician", message: "Prescription updated: Special lenses for viewing 'computer vegetables' more clearly.", time: "1 month ago", emoji: "👁️" },
  { title: "Commonwealth Secretary", message: "South Africa politely declines your offer to teach them 'proper caterpillar walking'.", time: "1 month ago", emoji: "🇿🇦" },
  { title: "Palace Engineer", message: "The automatic 'Clond Detection System' has been installed in all doorways.", time: "1 month ago", emoji: "🔧" },
  { title: "Royal Pharmacist", message: "Your prescription for 'Anti-Loud-Man Anxiety Medicine' is ready for collection.", time: "1 month ago", emoji: "💊" },
  { title: "Palace Kitchen", message: "Menu updated: All meals now served in 'caterpillar formation' as requested.", time: "1 month ago", emoji: "🍽️" },
  { title: "Royal Speech Coach", message: "Lesson 47: 'How to address parliament without mentioning Farm Hunter' scheduled tomorrow.", time: "1 month ago", emoji: "🎤" },
  { title: "Palace Gardener", message: "Rose bushes trained to grow in 'gentle gliding patterns' throughout the grounds.", time: "1 month ago", emoji: "🌺" },
  { title: "Royal Historian", message: "Your official biography chapter 'The Great Vortex Incident' needs fact-checking.", time: "1 month ago", emoji: "📜" },
  { title: "Commonwealth Office", message: "India respectfully requests explanation for the 47 packages of 'wiggly tooth wisdom'.", time: "1 month ago", emoji: "🇮🇳" },
  { title: "Palace Mechanic", message: "Royal limousine modified with 'silent leaf-gliding mode' as per specifications.", time: "1 month ago", emoji: "🚗" },
  { title: "Royal Jeweler", message: "The 'Emergency Biscuit Tiara' with hidden compartments is ready for coronation.", time: "1 month ago", emoji: "👑" },
  { title: "Palace IT Support", message: "Your 47 Farm Hunter accounts have been synchronized across all royal devices.", time: "1 month ago", emoji: "🔗" },
  { title: "Royal Composer", message: "The 'Clond Symphony in B-Minor' premiere has been... postponed indefinitely.", time: "1 month ago", emoji: "🎼" },
  { title: "Palace Security", message: "Night vision cameras show you practicing 'vortex lip techniques' at 4am daily.", time: "1 month ago", emoji: "👁️" },
  { title: "Royal Nutritionist", message: "Dietary recommendation: Perhaps vary from the all-christmas-roll meal plan?", time: "1 month ago", emoji: "🥕" },
  { title: "Commonwealth Games", message: "Olympic Committee's official response to 'Gentle Whispering Marathon': 'No thank you'.", time: "1 month ago", emoji: "🏃" },
  { title: "Palace Librarian", message: "Your 47-volume collection 'Advanced Caterpillar Techniques' has been properly shelved.", time: "1 month ago", emoji: "📖" },
  { title: "YouTube Support", message: "We noticed 247 attempts to search 'Queen England video not spiderman'. Need help?", time: "12 minutes ago", emoji: "📺" },
  { title: "William", message: "Granny, Kate says you can't hide Christmas cake in the armor suits anymore", time: "23 minutes ago", emoji: "🤴" },
  { title: "Palace Maintenance", message: "Found 15 wafers and 3 glasses of 'broaf' in throne room. Disposal needed?", time: "45 minutes ago", emoji: "🔧" },
  { title: "Royal Physician", message: "Reminder: Time for your daily medicine. Also found glue in your pocket again.", time: "1 hour ago", emoji: "💊" },
  { title: "Screen Saver Club", message: "New flying toasters pattern available! Click here to download safely!", time: "2 hours ago", emoji: "🖥️" },
  { title: "Buckingham Palace", message: "Ma'am, the tourists are asking why there's a skeleton in the west tower again", time: "4 hours ago", emoji: "🏰" },
  { title: "Royal Dentist", message: "Your Majesty, please stop trying to eat the Christmas ornaments", time: "5 hours ago", emoji: "🦷" },
  { title: "Harry", message: "Nan, Meghan wants to know if you're still mad about the Netflix thing", time: "7 hours ago", emoji: "👑" },
  { title: "Palace Kitchen", message: "We're out of 'broaf'. Should we order more mysterious brown liquid?", time: "8 hours ago", emoji: "🥤" },
  { title: "Royal Accountant", message: "Your eBay purchase of '50 pool noodles' has been approved for £847", time: "12 hours ago", emoji: "💷" },
  { title: "Computer Tutor", message: "Remember: YouTube is spelled with 'Y-o-u' not 'Y-o-u-T-u-n-e' Your Majesty", time: "1 day ago", emoji: "👨‍🏫" },
  { title: "Palace Security", message: "The armor collection is clanking again. Should we check for more skeletons?", time: "1 day ago", emoji: "⚔️" },
  { title: "Royal Photographer", message: "Ma'am, you've taken 89 photos of horses today. Memory card full.", time: "2 days ago", emoji: "📸" },
  { title: "Microsoft Word", message: "Your document 'Secret Princess Feeding Instructions' has been auto-saved", time: "2 days ago", emoji: "📝" },
  { title: "Palace Electrician", message: "Found more chewed wires. Suggest immediate corgi containment protocol.", time: "3 days ago", emoji: "⚡" },
  { title: "Anne", message: "Mother, the horses are asking for you. Also, please stop photographing them.", time: "3 days ago", emoji: "🐎" },
  { title: "Royal Butler", message: "Your Majesty, we found your kneecap in the garden shed. Shall we reattach?", time: "4 days ago", emoji: "🦴" },
  { title: "Contest Central", message: "Sorry, deceased individuals cannot win our bingo competition. Rules are rules.", time: "5 days ago", emoji: "🎰" },
  { title: "Palace Janitor", message: "Ma'am, the pearly gates keep appearing in the throne room. Normal?", time: "6 days ago", emoji: "🧹" },
  { title: "Edward", message: "Mummy, why does my computer keep showing ads for 'ultimate drummer fails'?", time: "1 week ago", emoji: "🥁" },
  { title: "Royal Snorkel Shop", message: "Your custom 'Death Tube 3000' snorkel has arrived! Free shipping to palace!", time: "1 week ago", emoji: "🤿" },
  { title: "Palace Glue Supplier", message: "Monthly glue delivery ready. Extra strong adhesive as requested.", time: "1 week ago", emoji: "🧪" },
  { title: "Tech Support", message: "Ma'am, turning brightness to 1000% is damaging your screen. Please stop.", time: "2 weeks ago", emoji: "🔆" },
  { title: "Royal Headphone Repair", message: "Your 47 pairs of 'very quiet headphones' are ready for pickup", time: "2 weeks ago", emoji: "🎧" },
  { title: "Contest Disqualification", message: "You've been banned from all giveaways for being technically deceased", time: "2 weeks ago", emoji: "🚫" },
  { title: "Palace Battery Supplier", message: "Computer doesn't use batteries Your Majesty. We've discussed this.", time: "3 weeks ago", emoji: "🔋" },
  { title: "YouTube Algorithm", message: "Based on your searches, recommended: 'Spiderman talks about computer drums'", time: "3 weeks ago", emoji: "🕷️" },
  { title: "Royal Anger Management", message: "Punching computers is not recommended. Anger redirection class at 2pm?", time: "3 weeks ago", emoji: "👊" },
  { title: "Camilla", message: "Charles keeps asking for computer help. I told him you're the expert now.", time: "1 month ago", emoji: "👸" },
  { title: "Royal Trash Service", message: "Please stop threatening to throw computer in garbage. We're concerned.", time: "1 month ago", emoji: "🗑️" },
  { title: "Palace WiFi", message: "Network 'QueenElizabeth_SecretBlog' is using 99% of bandwidth for horse photos", time: "1 month ago", emoji: "📶" },
  { title: "Afterlife Customer Service", message: "Welcome to death! Your complaint about 'still aging' has been filed.", time: "1 month ago", emoji: "👻" },
  { title: "Royal Face Recognition", message: "AI keeps identifying you as 'suspicious elderly person'. Should we adjust?", time: "1 month ago", emoji: "🤖" },
  { title: "Palace Night Watch", message: "Heard lengthargic groaning from throne room again. Should we investigate?", time: "2 months ago", emoji: "🌙" },
  { title: "Skeleton Disposal", message: "Your collection has exceeded storage limits. Consider donating to museum?", time: "2 months ago", emoji: "💀" },
  { title: "Royal Gaming", message: "High score achieved in Solitaire! 3 games won out of 847 attempts!", time: "2 months ago", emoji: "🎮" },
  { title: "International Relations", message: "Obama called asking about 'snorkeling incident'. Should we respond?", time: "2 months ago", emoji: "🌍" },
  { title: "Royal Memory Care", message: "Daily reminder: You are the Queen. Your name is Elizabeth. Today is Tuesday.", time: "3 months ago", emoji: "🧠" },
  { title: "Palace Lost & Found", message: "Found: 1 eye, 3 fingernails, assorted dignity. Claim at front desk.", time: "3 months ago", emoji: "👁️" },
  { title: "Swimming Instructor", message: "Ma'am, forgetting how to swim is not part of snorkeling technique", time: "3 months ago", emoji: "🏊‍♀️" },
  { title: "Putin's Office", message: "Vladimir keeps calling asking if you want to 'ride bears together'. Should we respond?", time: "15 minutes ago", emoji: "🇷🇺" },
  { title: "Biden Administration", message: "President Biden fell asleep during video call. You were showing him your spoon collection.", time: "32 minutes ago", emoji: "🇺🇸" },
  { title: "French Embassy", message: "Macron is upset you keep calling him 'that little French boy with the wrinkly wife'", time: "1 hour ago", emoji: "🇫🇷" },
  { title: "Xi Jinping's Office", message: "Chinese President confused why you keep sending him fortune cookies with threats inside", time: "2 hours ago", emoji: "🇨🇳" },
  { title: "Diplomatic Security", message: "Ma'am, you cannot challenge world leaders to 'computer typing contests' during summits", time: "3 hours ago", emoji: "🌐" },
  { title: "German Embassy", message: "Chancellor Scholz called asking why you shipped him 200 sausages with note 'SORRY ABOUT HITLER'", time: "4 hours ago", emoji: "🇩🇪" },
  { title: "Japanese Embassy", message: "Prime Minister Kishida politely asks you to stop calling him 'Anime Boy'", time: "6 hours ago", emoji: "🇯🇵" },
  { title: "Canadian PM", message: "Trudeau concerned about your offer to 'adopt him as spare grandson'", time: "8 hours ago", emoji: "🇨🇦" },
  { title: "Australian Embassy", message: "Your letter to Australia reading 'GIVE ME BACK MY CRIMINALS' caused diplomatic incident", time: "10 hours ago", emoji: "🇦🇺" },
  { title: "Turkish Embassy", message: "Erdogan is asking why you keep sending him Christmas turkeys with angry notes attached", time: "14 hours ago", emoji: "🇹🇷" },
  { title: "Vatican Security", message: "The Pope wants to know why you tried to confess your 'computer sins' for 4 hours", time: "18 hours ago", emoji: "🇻🇦" },
  { title: "Indian Embassy", message: "Prime Minister Modi confused by your peace proposal: 'just curry everything'", time: "1 day ago", emoji: "🇮🇳" },
  { title: "Mexican President", message: "AMLO wants clarification on your border wall plan: 'giant corgi fence'", time: "2 days ago", emoji: "🇲🇽" },
  { title: "Brazilian Embassy", message: "Bolsonaro received your Amazon purchase offer: '3 pounds and some old jewelry'", time: "2 days ago", emoji: "🇧🇷" },
  { title: "Saudi Crown Prince", message: "MBS politely declined your oil deal: 'Will trade for one good snorkel'", time: "3 days ago", emoji: "🇸🇦" },
  { title: "Swiss Embassy", message: "Your ransom note demanding 'ALL THE CHOCOLATE OR ELSE' has been filed appropriately", time: "3 days ago", emoji: "🇨🇭" },
  { title: "Egyptian Ambassador", message: "Your archaeological claim that 'pyramids look like my hats' has been noted", time: "5 days ago", emoji: "🇪🇬" },
  { title: "Iranian Embassy", message: "Ayatollah received your peace offering: 47 Christmas puddings and threatening letter", time: "6 days ago", emoji: "🇮🇷" },
  { title: "Israeli Embassy", message: "Your Middle East peace plan 'everyone should just be nicer' under review", time: "1 week ago", emoji: "🇮🇱" },
  { title: "South African Embassy", message: "Your demand to 'bring back apartheid but for computers' has caused confusion", time: "1 week ago", emoji: "🇿🇦" },
  { title: "Polish Embassy", message: "President Duda asks why you keep calling Poland 'East Germany's annoying cousin'", time: "1 week ago", emoji: "🇵🇱" },
  { title: "Norwegian Embassy", message: "Your application to 'be a Viking' has been politely declined by Oslo", time: "2 weeks ago", emoji: "🇳🇴" },
  { title: "Ukrainian Embassy", message: "Zelensky confused by your military aid offer: 'really angry corgis'", time: "2 weeks ago", emoji: "🇺🇦" },
  { title: "Dutch Embassy", message: "Your complaint that 'Holland is too flat and full of bicycles' filed under tourism", time: "2 weeks ago", emoji: "🇳🇱" },
  { title: "Spanish Embassy", message: "Your demand for 'Gibraltar back or I'm telling mum' caused 3-hour diplomatic meeting", time: "3 weeks ago", emoji: "🇪🇸" },
  { title: "Argentine Embassy", message: "Your Falklands negotiation strategy 'penguin fight club' deemed inappropriate", time: "3 weeks ago", emoji: "🇦🇷" },
  { title: "EU Parliament", message: "Your Brexit reversal plan 'everyone should just forget' surprisingly well-received", time: "1 month ago", emoji: "🇪🇺" },
  { title: "UN Security Council", message: "Your veto of 'being dead' has been overruled by mortality committee", time: "1 month ago", emoji: "🏛️" },
  { title: "William", message: "Mum, Kate says I left my balding cream in your bathroom again. Can you check?", time: "just now", emoji: "👑" },
  { title: "Royal Physician", message: "Reminder: Your 4pm appointment to discuss why you keep forgetting appointments.", time: "18 minutes ago", emoji: "⚕️" },
  { title: "Royal Physician", message: "Your blood pressure spikes every time someone mentions Harry and Meghan. Please breathe.", time: "1 week ago", emoji: "💗" },
  { title: "Royal Doctor", message: "Your pill organizer is empty again. Please stop feeding your medications to the corgis.", time: "1 day ago", emoji: "💊" },
  { title: "Royal Memory Care", message: "Note: Your reflection in the mirror is you, not 'that other Queen who lives here'.", time: "3 months ago", emoji: "🪞" },
  { title: "Royal Memory Care", message: "Daily reminder: You are the Queen. Your name is Elizabeth. Today is Tuesday.", time: "3 months ago", emoji: "🧠" },
  { title: "Royal Memory Care", message: "Important: The year is 2025.", time: "3 months ago", emoji: "📅" },
  { title: "Royal Memory Care", message: "Daily briefing: The 'strangers in fancy clothes' are visiting dignitaries, not intruders.", time: "3 months ago", emoji: "🛡️" },
  { title: "Royal Memory Care", message: "Reminder: You live in Buckingham Palace'.", time: "3 months ago", emoji: "🏛️" },
  { title: "Royal Dentist", message: "At last count, you have 16 remaining teeth. Consider eating fewer croissants.", time: "3 months ago", emoji: "🦷" },
  { title: "Royal Memory Care", message: "Reminder: Charles is your son", time: "3 months ago", emoji: "👨‍⚕️" },
  { title: "Royal Memory Care", message: "Daily briefing: The red boxes contain government papers", time: "3 months ago", emoji: "📋" },
  { title: "Royal Memory Care", message: "Daily reminder: You are the Queen. Your name is Elizabeth. Today is Tuesday.", time: "3 months ago", emoji: "🧠" },
  { title: "Royal Memory Care", message: "Daily briefing: You knight people with a sword. This is called an investiture.", time: "3 months ago", emoji: "⚔️" },
  { title: "Royal Memory Care", message: "Daily briefing: You own all the swans on the River Thames. This is an old law.", time: "3 months ago", emoji: "🦢" },
  { title: "Royal Memory Care", message: "Important: Parliament makes laws. No need to personally arrest lawbreakers.", time: "3 months ago", emoji: "🏛️" },
  { title: "Palace Theater", message: "‘Sword Juggler 3D’ may not be age-appropriate.", time: "3 days ago", emoji: "🎥" }
];